### ISSUE TITLE
getting error in running below command after cloning this repo and setting path

### ISSUE THREAD

**Issue by marshmello275** [citusdata/pg_cron#135] opened 2021-04-16 19:12 UTC
Machine : ubuntu:16.04
postgreSQL : 9.5
~/pg_cron-main$ make && sudo PATH=$PATH make install

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -g -O2 -DMAP_HUGETLB=0x40000 -fPIC -std=c99 -Wall -Wextra -Werror -Wno-unused-parameter -Wno-implicit-fallthrough -Iinclude -I/opt/PostgreSQL/10/include -I. -I./ -I/opt/PostgreSQL/10/include/postgresql/server -I/opt/PostgreSQL/10/include/postgresql/internal -I/opt/local/Current/include -D_GNU_SOURCE  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include  -c -o src/job_metadata.o src/job_metadata.c
src/job_metadata.c: In function ‘GetRoleOidIfCanLogin’:
src/job_metadata.c:380:14: error: ‘FormData_pg_authid {aka struct FormData_pg_authid}’ has no member named ‘oid’
  return rform->oid;
              ^
src/job_metadata.c:381:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
src/job_metadata.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-implicit-fallthrough’ [-Werror]
cc1: all warnings being treated as errors
<builtin>: recipe for target 'src/job_metadata.o' failed
make: *** [src/job_metadata.o] Error 1

**Comment by marcocitus** [comment] 2021-04-20 18:02
Thanks, this seems to be a regression on versions older than PostgreSQL 11.

**Comment by marshmello275** [comment] 2021-04-20 22:53
but i use postgres 9.5, am i suppose to use only postgresql 11 and above?

**Comment by juvette915** [comment] 2021-05-05 05:08
I install pg_cron on postgres version 12 and i scheduled the script below to delete job history from cron.job_run_details tables but when i run the script i get an error message.
script =  SELECT cron.schedule('0 0 * * *', $$DELETE 
 FROM cron.job_run_details 
 WHERE end_time < now() – interval '7 days'$$);

Error message = jobid          | 3
runid          | 3
               |  WHERE end_time < now() – interval '7 day'
status         | failed
return_message | ERROR: syntax error at or near "–"
start_time     | 2021-05-05 04:30:00.1103+00
end_time       | 2021-05-05 04:30:00.113867+00

**Comment by juvette915** [comment] 2021-05-05 05:09
Please i need help with this to correct the syntax error

**Comment by marcocitus** [comment] 2021-09-25 17:03
There was an issue on PostgreSQL <=11 that has been fixed on main and v1.4.1.

**Closed by marcocitus** 2021-09-25 17:03 UTC
Labels: bug

**Comment by marshmello275** [comment] 2021-09-27 04:40
thanks, it got cleared after the upgrade
