### ISSUE TITLE
cron.host is ignored

### ISSUE THREAD

**Issue by caseyandgina** [citusdata/pg_cron#224] opened 2023-01-04 00:53 UTC
Because of #200, I tried to configure pg_cron to use UNIX socket connections by setting cron.host to '/run/postgresql'.  But it's not working.

```
postgres=# show cron.use_background_workers;
 cron.use_background_workers 
-----------------------------
 off
(1 row)

postgres=# show cron.host;
    cron.host    
-----------------
 /run/postgresql
(1 row)
```

Logs show connections are still going to 127.0.0.1, not /run/postgresql as configured:

```
2023-01-04 00:44:00.005 UTC [3413564]: db=postgres,user=maintenance,app=[unknown],client=127.0.0.1 31/45 FATAL:  no pg_hba.conf entry for host "127.0.0.1", user "maintenance", database "postgres", no encryption                                                                                                    
2023-01-04 00:44:00.005 UTC [3413564]: db=postgres,user=maintenance,app=[unknown],client=127.0.0.1 31/45 DETAIL:  Client IP address resolved to "localhost", forward lookup matches.                                                                                                                         
2023-01-04 00:44:00.007 UTC [3412420]: LOG:  cron job 9 connection failed                                                                         
```

**Comment by marcocitus** [comment] 2023-01-06 12:37
Seems like a duplicate of #199

**Closed by marcocitus** 2023-01-06 12:37 UTC
